name: wearabouts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  local_auth: ^2.3.0
  provider: ^6.0.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/shoes.svg
    - Assets/homebackground.jpeg
    - Assets/jackets.svg
    - Assets/tops.svg
    - Assets/bottoms.svg
    - Assets/PictureKids.png
    - Assets/endangered_animals.jpg
    - Assets/food_donation.jpg
    - Assets/recycling_volunteers.jpg
    - Assets/studying_kid.jpg